name: Build and Release Chrome Extension (.crx)

on:
  push:
    branches:
      - main

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install crx packager
        run: npm install -g crx

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Generate random private key for signing
        run: |
          openssl genpkey -algorithm RSA -out key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -in key.pem -out key.pem

      - name: Pack extension to CRX
        run: |
          crx pack ./ -o extension.crx -p key.pem
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.vars.outputs.SHORT_SHA }}
          release_name: Release ${{ steps.vars.outputs.SHORT_SHA }}
          draft: false
          prerelease: false

      - name: Upload CRX to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.crx
          asset_name: extension_${{ steps.vars.outputs.SHORT_SHA }}.crx
          asset_content_type: application/x-chrome-extension

      - name: Cleanup key file and CRX
        run: |
          rm key.pem extension.crx
