name: Build and Release Chrome Extension (.crx)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install crx packager
        run: npm install -g crx

      - name: Get commit info
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "COMMIT_SUMMARY=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
          echo "COMMIT_BODY=$(git log -1 --pretty=%b)" >> $GITHUB_ENV

      - name: Save private key
        run: echo "${{ secrets.SIGNING_KEY }}" > key.pem

      - name: Pack extension to CRX
        run: |
          crx pack ./ -o Off-Youtube-Bullshit_${{ env.SHORT_SHA }}.crx -p key.pem
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.SHORT_SHA }}
          release_name: "Release ${{ env.SHORT_SHA }} - ${{ env.COMMIT_SUMMARY }}"
          body: ${{ env.COMMIT_BODY != '' && env.COMMIT_BODY || env.COMMIT_SUMMARY }}
          draft: false
          prerelease: false

      - name: Upload CRX to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Off-Youtube-Bullshit_${{ env.SHORT_SHA }}.crx
          asset_name: Off-Youtube-Bullshit_${{ env.SHORT_SHA }}.crx
          asset_content_type: application/x-chrome-extension

      - name: Cleanup key file and CRX
        run: |
          rm key.pem Off-Youtube-Bullshit_${{ env.SHORT_SHA }}.crx